# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quaterback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Team')),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(choices=[('MN', 'Minnesota'), ('FL', 'Florida')], max_length=2),
        ),
    ]
