# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20161204_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(choices=[('MO', 'Missouri'), ('MN', 'Minnesota'), ('FL', 'Florida'), ('GA', 'Georgia'), ('TX', 'Texas')], max_length=2),
        ),
    ]
