# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20161204_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(choices=[('GA', 'Georgia'), ('FL', 'Florida'), ('TX', 'Texas'), ('MO', 'Missouri'), ('MN', 'Minnesota')], max_length=2),
        ),
    ]
