# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20161204_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(choices=[('MN', 'Minnesota'), ('MO', 'Missouri'), ('TX', 'Texas'), ('FL', 'Florida'), ('GA', 'Georgia')], max_length=4),
        ),
    ]
