# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20161205_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='quaterback',
            name='passing_yards',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(choices=[('FL', 'Florida'), ('GA', 'Georgia'), ('TX', 'Texas'), ('MO', 'Missouri'), ('MN', 'Minnesota')], max_length=4),
        ),
    ]
