# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_auto_20161205_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(choices=[('MN', 'Minnesota'), ('FL', 'Florida'), ('GA', 'Georgia'), ('MO', 'Missouri'), ('TX', 'Texas')], max_length=4),
        ),
        migrations.AlterField(
            model_name='quaterback',
            name='interceptions',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quaterback',
            name='touchdowns',
            field=models.IntegerField(null=True),
        ),
    ]
